### PR TITLE
onedrive_client.js fixes for upload, download & create folder

### LINKED ISSUE #49: Lint error: 'options' is not defined
**Describe the bug**

When building the latest version of master, gulp fails with a lint error.

```
[11:02:32] Using gulpfile /****/chromeos-filesystem-onedrive/gulpfile.js
[11:02:32] Starting 'default'...
[11:02:32] Starting 'clean'...
[11:02:32] Finished 'clean' after 5.07 ms
[11:02:32] Starting 'lint'...
[11:02:33]
/****/chromeos-filesystem-onedrive/src/scripts/onedrive_client.js
  623:13  error  'options' is not defined  no-undef
  624:42  error  'options' is not defined  no-undef
  625:29  error  'options' is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)

[11:02:33] 'lint' errored after 712 ms
[11:02:33] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 3 errors
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

[11:02:33] 'default' errored after 721 ms
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Check out the latest version of master.
2. `npm install`
3. `gulp`

**Additional Notes**
If you disable the lint step in the gulp file, it does build & run ok (sort of).

Looking at the lines in the file it is referring to, for the first one in the file at-least, the `options` object hasn't been initialised at the point you are setting a value inside it; is it just a case of initialising it first, or was a pre-filled object supposed to be passed?

### LINKED ISSUE #51: Creating directory in OneDrive for Business fails
**Describe the bug**
Creating a directory in a OneDrive for Business mount fails.

From the Developer Console:
```json
{
  "error": {
    "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
    "message": "The property 'path' does not exist on type 'oneDrive.item'. Make sure to only use property names that are defined by the type.",
    "innerError": {
      "request-id": "b5e857a5-3ada-4f6f-84f9-8bda0c6d6dc1",
      "date": "2019-11-05T13:10:28"
    }
  }
}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Mount a OneDrive for Business drive.
2. In the menu, `New Folder`
or
2. Drag & drop an existing folder from "My Files" into the OneDrive.

**Expected behaviour**
Directory is created, allowing files to be added.

**Screenshots**
screenshot 1567433279

**ChromeOS Version**
 - Neverware CloudReady 76.4.69

### PR DESCRIPTION
**Pull request by iamacarpet**
* Create folder fix #51 
* Upload fix #49 
* Download fix for CORS preflight error when using OneDrive for Business

### CODE REVIEW

**Comment by iamacarpet** [comment]
Link to the Microsoft thread about the CORS problem still being a known bug:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/43

**Comment by iamacarpet** [comment]
Ok, so actually, that isn't uploads working for larger files.

It works on anything smaller than about 500KB (as before no uploads were working for me), but anything larger than that is still broken.

I did find the problem with the multi-part uploads done with `createUploadSession` though:

```json
{
    "error": {
        "code": "invalidRequest",
        "message": "The Content-Range header is missing or malformed."
    }
}
```

From Microsoft's documentation:

> Important: Your app must ensure the total file size specified in the Content-Range header is the same for all requests. If a byte range declares a different file size, the request will fail.

It looks like we were adding the `Content-Range` header, but the final bit at the end that is supposed to be the total length of the upload Microsoft should be expecting, isn't known by us until the very end (Chrome OS seems to only give us the length of the current data and the offset, not the total size to expect in the end), so we're currently just setting it to the length of the current chunk.

This causes uploads of any subsequent chunks to fail, as OneDrive already thinks it has received the full length (as instructed by us), so shuts off the upload session in the background.

Mozilla's documentation suggests for an unknown total length in a `Content-Range` header, you can specify `Content-Range: <start>-<end>/*`, however Microsoft's Graph API just reports this as invalid on the first chunk.

I can't see a way around this, apart from buffering the whole upload in an internal array (during the `writeFile` calls), then flushing the array out to OneDrive on `closeFile`, although obviously this wouldn't scale very well to large files, as I'm sure this was origionally intended to address.

Any ideas?

**Comment by droz36** [comment]
Couldn't you read the entire file, counting the data length of each call, then just discarding the data and adding the callback data length in a var until the file is completed, then you would be able to determine your actual file length? The main drawback to this is that you have to transfer the file twice.

**Comment by iamacarpet** [comment]
To my knowledge, we don’t have access to the original file, know anything about it or even a file handle.

The file system provider from us is just exposing an “fopen”, “fwrite”, “fclose” style interface where we give the OS a file handle, it writes out a few byes at a time via the fwrite stale call, then closes when complete - everything else is abstracted above us and we have no knowledge of source (of any kind), as Chrome OS itself isn’t handling the copy operation.

**Comment by iamacarpet** [comment]
Taking a further look this morning, it looks like building up the file contents and submitting them at the end is exactly how `v2-legacy` used to do it, except rather than trying to store the file contents in a memory array as I'd considered, it stores it in a temporary filesystem, with `window.requestFileSystem(window.TEMPORARY`.

It looks like we'll have to revert back to doing the same thing, although we can still keep chunked uploads when closing the file and performing the upload - I'm guessing it'll just mean that the file transfer bar will be inaccurate.

**Comment by iamacarpet** [comment]
Just to have covered all of our bases, I spent an hour or so researching Javascript Streams (from NodeJS) and how to use them to pipe into a request body using the NodeJS request class.

My assumption was that if this could be ported to the browser for this extension, it may allow, using Golang style channels, for us to keep writing out gradually to a single upload channel (go back to simple uploads) at the same time as Chrome OS thinks it is being written, to solve the progress bar problem.

However, it doesn't look like this is really supported at all in Javascript, as hidden in the source of the request package, even it says you can't pipe any more data via a stream once the outbound request is started - so I guess they don't support any kind of stream concept natively, the data has to be fixed at the point the request is initiated.

Looks like uploading on `fileClose` really is our only option.

**Comment by rooey** [comment]
> Taking a further look this morning, it looks like building up the file contents and submitting them at the end is exactly how `v2-legacy` used to do it, except rather than trying to store the file contents in a memory array as I'd considered, it stores it in a temporary filesystem, with `window.requestFileSystem(window.TEMPORARY`.

I had tried and failed at this previously but if you can see a way to make it work, then by all means give it a try.

**Comment by iamacarpet** [comment]
I managed to get the upload working using the simpleFileUpload function and it does work fairly well, with the big caveat that the Graph API only accepts uploads up to 4MB in size.

That probably would be enough for our needs, but I feel the need to try and implement some kind of failure in the code if the OS tries to write any more than that, before even attempting the upload.

This is sucking up a lot of time and to be honest, the staff using Chrome OS don't really seem that bothered, they are happy using the web version and introducing this might just confuse them further.

**Pull request merged**
